version: '3.4'

services:
  synchroniser:
    image: ${DOCKER_REGISTRY-}synchroniser
    build:
      context: .
      dockerfile: Synchroniser/Dockerfile
  db: 
     image: "mcr.microsoft.com/mssql/server"
     environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
        - "80:80"
